services:
  mongodb:
    image: mongo:7
    ports: ["27017:27017"]
    volumes:
      - mongo_data:/data/db

  elasticsearch:
    image: elasticsearch:9.3.4
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports: ["9200:9200"]

  redis:                          # ← new
    image: redis:7-alpine
    ports: ["6379:6379"]
    volumes:
      - redis_data:/data

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.4
    command: start-dev --import-realm --spi-theme-static-max-age=-1
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_SMTP_USER: ${SMTP_USER}
      KC_SMTP_PASSWORD: ${SMTP_PASSWORD}
      KC_SPI_LOGIN_PROTOCOL_OPENID_CONNECT_LEGACY_LOGOUT_REDIRECT_URI: http://localhost:5173
    ports: ["8180:8080"]
    volumes:
      - ./keycloak/realm-export.json:/opt/keycloak/data/import/realm.json
      - ./keycloak/themes:/opt/keycloak/themes

volumes:
  mongo_data:
  redis_data:                     # ← new